services:
  wordlegame:
    build: ./wordlegame
    ports:
      - "8000:8000"

  statservice:
    build: ./statservice
    ports:
      - "8001:8001"
    environment:
      - WORDLE_API_URL=http://wordlegame:8000
    depends_on:
      - wordlegame
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - wordlegame
