services:
  wordlegame:
    build: ./wordlegame
    expose:
      - "8000"

  statservice:
    build: ./statservice
    expose:
      - "8001"
    environment:
      - WORDLE_API_URL=http://wordlegame:8000
    depends_on:
      - wordlegame
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - wordlegame
