[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:gunicorn]
command=gunicorn -w 3 -b 0.0.0.0:8000 "wordlegame:create_app()"
directory=/opt/wordlegame
autostart=true
autorestart=true
stdout_logfile=/var/log/gunicorn.log
redirect_stderr=true