[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:gunicorn]
command=gunicorn -w 3 -b 0.0.0.0:8000 "wordlegame:create_app()"
directory=/opt/wordlegame
autostart=true
autorestart=true
stdout_logfile=/var/log/gunicorn.log
redirect_stderr=true